[project]
name = "searxng-mcp"
version = "0.1.0"
description = "Searxng MCP Server"
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
license-files = ["LICENSE"]
dependencies = [
    "httpx>=0.28.1",
    "pydantic>=2.11.7",
]

[project.urls]
Homepage = "https://github.com/gkzhb/crawl4ai-mcp-py"
Repository = "https://github.com/gkzhb/crawl4ai-mcp-py"
Issues = "https://github.com/gkzhb/crawl4ai-mcp-py/issues"

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"
