[project]
name = "crawl4ai-mcp"
version = "0.1.0"
description = "Minimum MCP server to convert web2md"
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
license-files = ["LICENSE"]
dependencies = [
    "crawl4ai>=0.7.4",
    "playwright-stealth>=2.0.0",
]

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"
