[project]
name = "searxng-mcp-py"
version = "0.1.0"
description = "Searxng MCP Server"
readme = "README.md"
requires-python = ">=3.11"
license = {text = "MIT"}
license-files = ["LICENSE"]
dependencies = [
    "httpx>=0.28.1",
    "pydantic>=2.11.7",
]
