[project]
name = "agent-skills-mcp-gkzhb"
version = "0.1.1"
description = "Agent Skills MCP Server"
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
license-files = ["LICENSE"]
dependencies = [
    "fastmcp>=2.11.3",
    "pydantic>=2.11.7",
    "pyyaml>=6.0.1",
]

[project.scripts]
agent-skills = "agent_skills_mcp_gkzhb.main:main"

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"
